### ISSUE TITLE
build error: character too large for enclosing character literal type

### ISSUE THREAD

**Issue by patrickt** [eno-lang/tree-sitter-eno#1]
Running `tree-sitter test` produces the following error when compiling `scanner.cc`:

```
emcc command failed - src/scanner.cc:88:32: error: character too large for enclosing character literal type
           lexer->lookahead == '\uFEFF' ||
                               ^
src/scanner.cc:89:32: error: character too large for enclosing character literal type
           lexer->lookahead == '\u2060' ||
                               ^
src/scanner.cc:90:32: error: character too large for enclosing character literal type
           lexer->lookahead == '\u200B';
```

**Comment by simonrepp** [comment]
I've encountered this myself - if I remember correctly:
- You can comment out the affected lines for the time being if you just want to work on stuff (that's what I did so far), these are more exotic whitespace cases which of course matter, but are irrelevant for the overall implementation and general testing.
- It only occurrs in certain compilation scenarios (when building for the wasm target?)
- I don't have a solution yet!
- If you find one I'd be much obliged :)

In any case, thanks for the report! Glad about your interest in this, let me know if you have more questions and/or issues!

**Comment by patrickt** [comment]
This looks like it might be a tree-sitter bug. @maxbrunsfeld, have you ever seen anything like this before?

**Comment by patrickt** [comment]
I fixed it by removing the character syntax:
```c
  inline bool is_horizontal_whitespace(TSLexer *lexer) {
    return lexer->lookahead == ' ' ||
           lexer->lookahead == '\t' ||
           lexer->lookahead == 0xFEFF ||
           lexer->lookahead == 0x2060 ||
           lexer->lookahead == 0x200B;
  }
```

**Comment by maxbrunsfeld** [comment]
Yeah, I don't think `'\uFEFF'` is a valid C/C++ expression. Single quoted character literals are of type `char`, which is almost always an 8-bit value. The largest numerical `char` value is `0xFF`.

In more recent versions of C++, you can use a `U` prefix (e.g. `U'\uFEFF'`). I think the normal way to write numbers like this is to just use integer syntax, like @patrickt said ☝️ .

**Comment by simonrepp** [comment]
Very cool, thanks patrick for the fix and max for the additional insight, appreciate it!

Commited in c059967d243487c1c2f567bd56c1d40c9a92dbe4
